quarkus.http.port=8084

quarkus.datasource.db-kind=mysql
quarkus.datasource.reactive.url=vertx-reactive:mysql://localhost:3306/journal_db
quarkus.datasource.username=journalapp_user
quarkus.datasource.password=journalpass

quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true